---
language: ruby
cache: bundler
sudo: false
before_install:
  - rm Gemfile.lock || true
  - gem install bundler --pre
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
script: bundle exec rake test
env:
#  - PUPPET_VERSION="~> 3.3.0"
#  - PUPPET_VERSION="~> 3.4.0"
#  - PUPPET_VERSION="~> 3.5.0" STRICT_VARIABLES=yes
#  - PUPPET_VERSION="~> 3.6.0" STRICT_VARIABLES=yes
#  - PUPPET_VERSION="~> 3.7.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.8" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 4.0" STRICT_VARIABLES=yes
matrix:
  exclude:
  - rvm: 2.2.0
    env: PUPPET_VERSION="~> 3.8.0"
  - rvm: 2.3.0
    env: PUPPET_VERSION="~> 3.8.0"
