name          'danieldreier-autosign'
version       '0.1.0'
source        'https://github.com/danieldreier/puppet-autosign'
author        'danieldreier'
license       'Apache 2.0'
summary       'Manage certificate autosigning using the autosign gem'
description   ''
project_page  'https://github.com/danieldreier/puppet-autosign'

dependency 'puppetlabs/stdlib'
